[versions]
minecraft = "26.2"
kotlin = "2.4.10"
loaderfabric = "0.19.3"
loaderkotlin = "1.13.13+kotlin.2.4.10"
fapi = "0.159.0+26.2"
loom = "1.17.20"
devauth = "1.2.2"
olympus = "1.9.4"
resourcefullib = "5.0.0"
modmenu = "20.0.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader-fabric = { module = "net.fabricmc:fabric-loader", version.ref = "loaderfabric" }
loader-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "loaderkotlin" }
fapi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fapi" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
olympus = { module = "earth.terrarium.olympus:olympus-fabric-26.2", version.ref = "olympus" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
resourcefullib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-26.2", version.ref = "resourcefullib" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
